### ISSUE TITLE
关于语料数据文件“corpus.tar.gz”的咨询

### ISSUE THREAD

**Issue by Neo-Luo** [dreamszl/dtopwords#1]
您好！

我最近的研究参考了您的文章《Domain-Specific New Words Detection in Chinese》，因此看到了这个github的代码，但您好像忘记上传语料数据 文件“corpus.tar.gz”了。如果方便的话能否上传或者发给我邮箱一份呢？

十分谢谢！
__________
Neo (Beihang Univesrsity)
e-mail: smoothwind@foxmail.com

**Comment by dreamszl** [comment]
抱歉，修改完 readme 之后把 corpus.tar.gz 忘记了，下载链接：https://drive.google.com/open?id=0B_tvb3s-yy6fc1hzUGdSSzFNLTg
