### ISSUE TITLE
请问这个路径问题应该怎么解决好？

### ISSUE THREAD

**Issue by lydemo** [dreamszl/dtopwords#2]
E:\dtopword>python pipeline.py corpus/c4x@TsinghuaX@30240184X.txt result.txt result1.txt
命令语法不正确。
命令语法不正确。
'split' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "pipeline.py", line 103, in <module>
    generate_domain_words(src_path, dtop_res_path)
  File "E:\dtopword\dtopwords.py", line 336, in generate_domain_words
    initialize_static_files(trg_files)
  File "E:\dtopword\dtopwords.py", line 99, in initialize_static_files
    init_dict(tfp, cnp, inp)
  File "E:\dtopword\dtopwords.py", line 106, in init_dict
    generate_all_ngram(src_path, cn_path, len_threshold, fre_threshold, splitor=splitor)
  File "E:\dtopword\ngram.py", line 486, in generate_all_ngram
    generate_large_ngram_by_filtering(input_file_path, input_file_path + '_tmp%d' % i, gram_num=i, filter_num=filter_num, sort=True, filter_function=punctuation_filter, merge=False, splitor=splitor)
  File "E:\dtopword\ngram.py", line 257, in generate_large_ngram_by_filtering
    piece_file_list = [(f, os.path.join(tmp_dir, f)) for f in os.listdir(tmp_dir)]
WindowsError: [Error 3] : '/tmp/large_ngram_pieces_c4x@TsinghuaX@30240184X.txt.pun_filtered/*.*'

我发现只按readme里面的执行的话提示缺路径参数，所以在setting.py里面加入USE_RULE0 = 1这样的初始化语句，但是会蹦出上面的错误，应该是路径的问题，不懂怎么解决好呢？

**Comment by dreamszl** [comment]
@lydemo 抱歉，我也好久没有跑了，我这两天看一下回复你

**Comment by lydemo** [comment]
好的，因为我还在研究这个程序，我是把pipeline.py里面filter那部分的注释掉了才正常运行的：
if __name__ == '__main__':
    src_path = sys.argv[1]
    trg_path = sys.argv[2]
    # if FILTER_BY_TEMP2:
    #     seged_file_path = sys.argv[3]
    # dtop_res_path = os.path.join(settings.ROOT_DIR, 'results/dtop_res.txt')
    # generate_domain_words(src_path, dtop_res_path)
    # filter_by_threshold(src_path, dtop_res_path, trg_path)
    #
    # if FILTER_BY_TEMP2:
    #     filter_by_tempS(seged_file_path, trg_path)

这样大概不能生成最后的结果了，有的没有执行，我再看看怎么样可以生成最后的结果

**Comment by dreamszl** [comment]
你可以尝试只执行 generate_domain_words() 函数，这个是 dtopwords 算法的函数，其他只是一些后处理，可以不执行。

**Comment by lydemo** [comment]
只执行函数的话也是会出现上面的错误，暂时不懂是什么原因出现的

**Comment by lydemo** [comment]
是的，在Linux下生成dtop_res.txt就是最后结果吗？

**Comment by dreamszl** [comment]
是的，是 dtopwords 本身的结果
