### ISSUE TITLE
请问词典可以换么？

### ISSUE THREAD

**Issue by lydemo** [dreamszl/dtopwords#3]
想做一个类似于补充新词到已有词典的工作，请问初始的词典可以换么？

**Comment by dreamszl** [comment]
你是指什么词典呢？算法用到的词典么？算法本身并没有用到初始词典，只用到了在一个背景语料库的单字 ngram 的频次，是 corpus 目录下的 score_dict_fre.json 。
这个文件本质上只是一个单字 ngram 频次相关的一个 score 替换成你想要的即可。具体生成方法可以参考 dtopwords.py 里面的 fre_score() 函数。

**Comment by dreamszl** [comment]
如果你需要替换背景语料库，可以直接替换该 score_dict_fre.json 即可。

**Comment by lydemo** [comment]
想问一下背景语料库汉字后面的数字是什么含义？

**Comment by dreamszl** [comment]
你可以直接看 dtopwords.py 里的 fre_score() 函数
