### ISSUE TITLE
Question about evaluation Metric

### ISSUE THREAD

**Issue by YingZhuY** [dreamszl/dtopwords#5]
Hello.
最近在读这篇论文 [Chen, A. and Sun, M., 2017, August. Domain-specific new words detection in Chinese. In Proceedings of the 6th joint conference on lexical and computational semantics (* SEM 2017) (pp. 44-53)]. 关于 Evaluation Metric 节 MAP 中的 P(k) 函数有点疑惑，能求一份详细的评估部分代码吗？
Thanks.

**Comment by chenaoXD** [comment]
emmmmm 这个代码有点太久远了，找了找没找到。不过总体计算是非常简单的，你可以参考：https://web.stanford.edu/class/cs276/handouts/EvaluationNew-handout-1-per.pdf 里的第 4 页。基本来讲计算方式就和名字是一样的 (Mean) Average Precision，（mean 在我们这种二分类的情况下可以忽略）差不多就是把 前 1 个结果的 percision-p(1)，前 2 个结果的 precision-p(2)...前 n 个结果的 precision-p(n) 取个平均值即可。
